name: Deploy to ECR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: 335037124578.dkr.ecr.ap-northeast-2.amazonaws.com/ecr-repo

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region $AWS_REGION \
        | docker login --username AWS --password-stdin $ECR_REPOSITORY

    - name: Build, tag, and push image to ECR
      id: build-image
      run: |
        GIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
        IMAGE_TAG=$ECR_REPOSITORY:$GIT_HASH
        docker build -t $IMAGE_TAG .
        docker push $IMAGE_TAG
        echo "image=$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Checkout deployment repository
      uses: actions/checkout@v4
      with:
        repository: bespin-cicd/argocd-kube
        token: ${{ secrets.MY_GITHUB_TOKEN }}

    - name: Update deployment.yaml and push
      run: |
        GIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
        sed -i "16s|.*|      - image: $ECR_REPOSITORY:$GIT_HASH|g" deployment.yaml
        git config --global user.email "bespin.cicd@gmail.com"
        git config --global user.name "Seungsuk Ryoo"
        git add .
        git commit -am "Inject Tag" || echo "No changes to commit"
        git push

